services:
  - type: redis
    name: social-book-redis
    ipAllowList: []

  - type: web
    name: PerfectMatch
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne social_book.asgi:application"
    preDeployCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-y0ur$uperSecr3tKey1234567890
      - key: REDIS_URL
        fromService:
          type: redis
          name: social-book-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: perfectmatch-db
          property: connectionString
