databases:
  - name: perfectmatch-db
    databaseName: perfectmatch_db_fzvv
    user: perfectmatch_db_fzvv_user

services:
  - type: web
    name: PerfectMatch
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p $PORT social_book.asgi:application"
    preDeployCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      echo "from django.contrib.auth import get_user_model; \
      User = get_user_model(); \
      User.objects.filter(username='lolamo').exists() or \
      User.objects.create_superuser('lolamo', 'lolamo@example.com', 'lolamo1231123')" \
      | python manage.py shell
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "django-insecure-y0ur$uperSecr3tKey1234567890"
      - key: ALLOWED_HOSTS
        value: "perfectmatch-0uig.onrender.com,127.0.0.1,localhost"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://perfectmatch-0uig.onrender.com"
      - key: REDIS_URL
        value: "rediss://default:AbK9AAIjcDE3NjY3Y2M0N2I0NjY0OTgyYTljNTQ4ZDExMjZhMDJkM3AxMA@nearby-crow-45757.upstash.io:6379"
      - key: DATABASE_URL
        fromDatabase:
          name: perfectmatch-db
          property: connectionString
      - key: CLOUDINARY_URL
        value: "cloudinary://817192711611655:8t-1T4p26-GMGH5JDUa5Mg-8suQ@dwakgnjvw"
