# Generated by Django 5.2 on 2025-07-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='https://res.cloudinary.com/8t-1T4p26-GMGH5JDUa5Mg-8suQ/image/upload/v1234567890/blank_profile_picture.png', upload_to='profile_images/'),
        ),
    ]
