# Generated by Django 5.2 on 2025-07-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='https://res.cloudinary.com/.../blank_profile_picture.png', max_length=500, upload_to='profile_images/'),
        ),
    ]
