# Generated by Django 5.2 on 2025-07-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profileimg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeletionlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who performed the account deletion (null = self-deletion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletion_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountdeletionlog',
            name='deletion_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountdeletionlog',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
