# Generated by Django 5.2 on 2025-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accountdeletionlog_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_images/'),
        ),
    ]
