# Generated by Django 5.2 on 2025-05-27 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_image_postimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images/'),
        ),
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_account_username', models.CharField(help_text='Username of the account that was deleted.', max_length=150)),
                ('deletion_timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the account was deleted.')),
                ('reason', models.TextField(blank=True, help_text='Optional reason provided for the account deletion.', null=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who performed the account deletion (will be null for self-deletion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Deletion Log',
                'verbose_name_plural': 'Account Deletion Logs',
                'ordering': ['-deletion_timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
